# Generated by Django 3.2 on 2022-03-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Подразделение')),
                ('divisions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departament', to='control.division', verbose_name='Подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='GroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Групповая политика')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Основной контент')),
            ],
            options={
                'verbose_name': 'Групповую политиику',
                'verbose_name_plural': 'Групповые политики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemaParams',
            fields=[
                ('type', models.SlugField(allow_unicode=True, choices=[('HOST', 'host'), ('USER', 'user')], default='HOST', max_length=10, primary_key=True, serialize=False, verbose_name='Типы')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='DomenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domenuser', to='control.division', verbose_name='Подразделения')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='division',
            name='group_policy',
            field=models.ManyToManyField(blank=True, related_name='policy', to='control.GroupPolicy', verbose_name='групповые политики'),
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Компьютеры')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='control.division', verbose_name='Подразделения')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
