# Generated by Django 3.2 on 2022-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygrouppolicy',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Наименование политики'),
        ),
    ]
