# Generated by Django 3.2 on 2022-04-18 06:47

from django.db import migrations

def create_schema(apps, schema_editor):
    
    ParamsSchema = apps.get_model('control', 'ParamsSchema')
    obj, create = ParamsSchema.objects.get_or_create(type="USER")
    if create:
        obj.body=  "{\"system\":{\"autorun\":{\"apps\":[{\"name\":\"\",\"cmd\":\"\",\"icon\":\"\"}],\"links\":[{\"name\":\"\",\"url\":\"\"}]},\"datetime\":{\"timezone\":\"\",\"time_format\":\"\"},\"env_vars\":{\"settings\":{\"source\":\"\"},\"vars\":[{\"name\":\"\",\"value\":\"\"}]},\"mime_types\":{\"associations\":[{\"app\":\"\",\"types\":\"\"}],\"mailto\":\"\",\"http\":\"\"}},\"desktop\":{\"start_menu\":{\"apps\":[{\"name\":\"\",\"cmd\":\"\",\"icon\":\"\"}],\"links\":[{\"name\":\"\",\"url\":\"\"}],\"folders\":[{\"name\":\"\"}]},\"quicklaunch\":{\"apps\":[{\"name\":\"\",\"cmd\":\"\",\"icon\":\"\"}],\"links\":[{\"name\":\"\",\"url\":\"\"}],\"folders\":[{\"name\":\"\"}]}},\"hardware\":{\"power_mgmt\":{\"notifications\":{\"batt_low\":\"\",\"batt_full\":\"\",\"plugged_in\":\"\",\"unplugged\":\"\"},\"screen_timeout\":600,\"lock_when_screen_off\":true,\"sleep_timeout\":1200,\"script_timeout\":300,\"script_after_timeout\":\"\"}}},\"host\":{\"system\":{\"datetime\":{\"server\":\"\"},\"env_vars\":{\"vars\":[{\"name\":\"\",\"value\":\"\"}]},\"mime_types\":{\"associations\":[{\"app\":\"\",\"types\":\"\"}]}},\"network\":{\"firewall\":{\"rules\":[{\"name\":\"\",\"direction\":\"\",\"port\":69,\"allow\":false}],\"options\":{\"log_level\":3,\"profile\":\"\",\"active\":true}}},\"security\":{\"quotas\":{\"per_device\":[{\"device\":\"\",\"limit\":\"\"}],\"per_user\":[{\"user\":\"\",\"device\":\"\",\"limit\":\"\"}],\"per_group\":[{\"group\":\"\",\"device\":\"\",\"limit\":\"\"}],\"admin_email\":\"\"},\"system_protection\":{\"integrity_control\":{\"enabled\":true,\"level\":63},\"filesystem_protection\":{\"enabled\":true,\"exclude\":\"\"},\"isolate_services\":true}}}"
        obj.save()
    obj1, created = ParamsSchema.objects.get_or_create(type="HOST", body="{\"system\":{\"datetime\":{\"server\":\"\"},\"env_vars\":{\"vars\":[{\"name\":\"\",\"value\":\"\"}]},\"mime_types\":{\"associations\":[{\"app\":\"\",\"types\":\"\"}]}},\"network\":{\"firewall\":{\"rules\":[{\"name\":\"\",\"direction\":\"\",\"port\":69,\"allow\":false}],\"options\":{\"log_level\":3,\"profile\":\"\",\"active\":true}}},\"security\":{\"quotas\":{\"per_device\":[{\"device\":\"\",\"limit\":\"\"}],\"per_user\":[{\"user\":\"\",\"device\":\"\",\"limit\":\"\"}],\"per_group\":[{\"group\":\"\",\"device\":\"\",\"limit\":\"\"}],\"admin_email\":\"\"},\"system_protection\":{\"integrity_control\":{\"enabled\":true,\"level\":63},\"filesystem_protection\":{\"enabled\":true,\"exclude\":\"\"},\"isolate_services\":true}}}")
    if created:
        obj.body= "{\"system\":{\"datetime\":{\"server\":\"\"},\"env_vars\":{\"vars\":[{\"name\":\"\",\"value\":\"\"}]},\"mime_types\":{\"associations\":[{\"app\":\"\",\"types\":\"\"}]}},\"network\":{\"firewall\":{\"rules\":[{\"name\":\"\",\"direction\":\"\",\"port\":69,\"allow\":false}],\"options\":{\"log_level\":3,\"profile\":\"\",\"active\":true}}},\"security\":{\"quotas\":{\"per_device\":[{\"device\":\"\",\"limit\":\"\"}],\"per_user\":[{\"user\":\"\",\"device\":\"\",\"limit\":\"\"}],\"per_group\":[{\"group\":\"\",\"device\":\"\",\"limit\":\"\"}],\"admin_email\":\"\"},\"system_protection\":{\"integrity_control\":{\"enabled\":true,\"level\":63},\"filesystem_protection\":{\"enabled\":true,\"exclude\":\"\"},\"isolate_services\":true}}}"
        obj1.save()
    
    
def create_orgunit(apps, schema_editor):
    OrgUnit = apps.get_model('control', 'OrgUnit')
    cond = OrgUnit.objects.all()
    obj, created = OrgUnit.objects.get_or_create(name="root")
    if created and len(cond) > 0:
        obj.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_historygrouppolicy_name'),
    ]

    operations = [
        migrations.RunPython(create_orgunit),
        migrations.RunPython(create_schema),
    ]
