# Generated by Django 3.2 on 2022-03-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20220320_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='types',
        ),
    ]
